version: 2.0.{build}
max_jobs: 1
image: Visual Studio 2015
matrix:
  fast_finish: true
  allow_failures:
  - platform: x86
    configuration: Debug
  - platform: x64
    configuration: Debug
  - platform: x86
    configuration: Release
  - platform: x64
    configuration: Release

platform:
- Win32
- x64

cache:
- cmake-build

configuration:
- Debug
- Release

install:
- powershell -Command "(gc .gitmodules) -replace 'git@github.com:', 'https://github.com/' | Out-File .gitmodules" -encoding UTF8
- git submodule update --init --recursive

before_build:
- if not exist cmake-build mkdir cmake-build
- cd cmake-build
- if "%PLATFORM%"=="Win32" if "%CONFIGURATION%"=="Debug" cmake -G "Visual Studio 14 2015" .. -Dtest=ON
- if "%PLATFORM%"=="x64" if "%CONFIGURATION%"=="Debug" cmake -G "Visual Studio 14 2015 Win64" .. -Dtest=ON
- if "%PLATFORM%"=="Win32" if "%CONFIGURATION%"=="Release" cmake -G "Visual Studio 14 2015" .. -Dtest=ON
- if "%PLATFORM%"=="x64" if "%CONFIGURATION%"=="Release" cmake -G "Visual Studio 14 2015 Win64" .. -Dtest=ON

build:
  parallel: true
  project: cmake-build/COLLADA2GLTF.sln

after_build:
- for /R . %%f in (*.exe *.lib *.pdb *.dll) do copy %%f .
- for /F "delims=-" %%a in ("%APPVEYOR_REPO_BRANCH%") do set RELEASE=%%a
- 7z a COLLADA2GLTF-"%RELEASE%"-windows-"%CONFIGURATION%"-"%PLATFORM%".zip
  .\*.exe
  .\*.lib
  .\*.pdb
  .\*.dll

test_script:
- "%CONFIGURATION%\\COLLADA2GLTF-test.exe"
- "GLTF\\%CONFIGURATION%\\GLTF-test.exe"

artifacts:
- path: cmake-build/*.zip
  name: built-zip

deploy:
  description: Live build of latest master from CI
  provider: GitHub
  auth_token:
    secure: dNmT53aWZs5g0xiT713qZYpumGQTi7qzXPXKWO9Ub/X1IQfeb/uo81Zk+4kFf8U4
  on:
    appveyor_repo_tag: true
  force_update: true
