version: 2.0.{build}
max_jobs: 1
image: Visual Studio 2015
matrix:
  fast_finish: true
  allow_failures:
  - platform: x86
    configuration: Debug
  - platform: x64
    configuration: Debug
  - platform: x86
    configuration: Release
  - platform: x64
    configuration: Release

platform:
- Win32
- x64

configuration:
- Debug
- Release

cache:
- cmake-build/dependencies -> appveyor.yml, .gitmodules
- cmake-build/GLTF/dependencies -> appveyor.yml, .gitmodules

install:
- powershell -Command "(gc .gitmodules) -replace 'git@github.com:', 'https://github.com/' | Out-File .gitmodules" -encoding UTF8
- git submodule update --init --recursive

before_build:
- if not exist cmake-build mkdir cmake-build
- cd cmake-build
- IF "%PLATFORM%"=="Win32" cmake -G "Visual Studio 14 2015" .. -Dtest=ON
- IF "%PLATFORM%"=="x64" cmake -G "Visual Studio 14 2015 Win64" .. -Dtest=ON

build:
  parallel: true
  project: cmake-build/COLLADA2GLTF.sln

after_build:
- for /R . %%f in (*.exe *.lib *.pdb *.dll) do copy %%f .
- for /F "delims=-" %a in ("1.0-release") do set RELEASE=%a
- 7z a COLLADA2GLTF-windows-"%RELEASE"-"%CONFIGURATION%"-"%PLATFORM%".zip
  .\*.exe
  .\*.lib
  .\*.pdb
  .\*.dll

test_script:
- "%CONFIGURATION%\\COLLADA2GLTF-test.exe"
- "GLTF\\%CONFIGURATION%\\GLTF-test.exe"

artifacts:
- path: cmake-build/*.zip
  name: built-zip

deploy:
  provider: GitHub
  auth_token:
    secure: Nh+ZPhrI2P9EmI/+YlHiY7Roj/4dYHM0XMXr8rFX6O8q9mujEMbBNdbLw0QZ5Nq7
  on:
    appveyor_repo_tag: true
  force_update: true
